---
# tasks file for lighthouse

- name: Copy Lighthouse to webfolder
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_url }}"
    dest: "{{ lighthouse_web_folder }}"
    version: "{{ lighthouse_version }}"
